import { db, usersTable, rightsArticlesTable, complaintTemplatesTable, journeysTable, schemesTable, learningContentTable, legalAidProvidersTable, notificationsTable } from "@workspace/db";
import bcrypt from "bcryptjs";
import { sql } from "drizzle-orm";

async function seed() {
  console.log("Starting seed...");

  // Admin user
  const adminHash = await bcrypt.hash("admin123", 12);
  const userHash = await bcrypt.hash("demo123", 12);

  await db.insert(usersTable).values([
    { fullName: "Admin User", email: "admin@nyayasetu.in", passwordHash: adminHash, preferredLanguage: "en", role: "admin", mobile: "9000000000" },
    { fullName: "Priya Sharma", email: "priya@example.com", passwordHash: userHash, preferredLanguage: "en", role: "user", mobile: "9876543210", address: "123 MG Road, Mumbai" },
  ]).onConflictDoNothing();

  // Rights Articles
  await db.insert(rightsArticlesTable).values([
    {
      title: "Right to Equal Pay for Equal Work",
      summary: "Women are entitled to equal remuneration for the same work as male employees under the Equal Remuneration Act.",
      content: "The Equal Remuneration Act, 1976 mandates that employers must pay equal wages to both male and female workers performing the same work or work of a similar nature. Any employer who fails to comply with this provision is liable to punishment.\n\nKey provisions:\n- No employer can discriminate between male and female employees in the matter of wages\n- The Act applies to all establishments and factories\n- Employers must maintain registers showing wages paid to all employees\n\nWhat to do if your rights are violated:\n1. File a complaint with the Labour Commissioner\n2. Approach the Labour Court under the Industrial Disputes Act\n3. File a complaint under the Equal Remuneration Act through the designated authority",
      category: "womens-rights",
      relevantLaws: JSON.stringify(["Equal Remuneration Act, 1976", "Minimum Wages Act, 1948", "Payment of Wages Act, 1936"]),
      legalProvisions: JSON.stringify(["Section 4 - Duty of employer to pay equal remuneration", "Section 5 - Discrimination not to be made while recruiting", "Section 8 - Maintenance of registers"]),
      governmentResources: JSON.stringify(["Ministry of Labour and Employment - labour.gov.in", "National Commission for Women - ncw.nic.in"]),
    },
    {
      title: "Protection from Sexual Harassment at Workplace",
      summary: "The POSH Act 2013 protects women from sexual harassment at the workplace and mandates Internal Complaints Committees.",
      content: "The Sexual Harassment of Women at Workplace (Prevention, Prohibition and Redressal) Act, 2013 (commonly known as the POSH Act) provides protection to women against sexual harassment at the workplace.\n\nEvery employer with 10 or more workers must constitute an Internal Complaints Committee (ICC). The ICC must have at least 50% women members.\n\nDefinition of sexual harassment:\n- Unwelcome physical contact and advances\n- Demand or request for sexual favors\n- Making sexually colored remarks\n- Showing pornography\n- Any other unwelcome physical, verbal or non-verbal conduct of sexual nature\n\nSteps to take if harassed:\n1. Report the matter to the ICC within 3 months of the incident\n2. If no ICC exists, approach the Local Complaints Committee (LCC)\n3. File a criminal complaint with the police under Section 354A IPC",
      category: "womens-rights",
      relevantLaws: JSON.stringify(["POSH Act, 2013", "Indian Penal Code Section 354A", "Protection of Women from Domestic Violence Act, 2005"]),
      legalProvisions: JSON.stringify(["Section 2 - Definitions", "Section 4 - Constitution of Internal Complaints Committee", "Section 9 - Complaint of sexual harassment"]),
      governmentResources: JSON.stringify(["Ministry of Women and Child Development - wcd.nic.in", "SHe-Box Portal - shebox.wcd.gov.in"]),
    },
    {
      title: "Consumer Rights Under Consumer Protection Act 2019",
      summary: "As a consumer, you have six fundamental rights including the right to safety, information, choice, and redressal.",
      content: "The Consumer Protection Act, 2019 replaced the 1986 Act and provides stronger protections for consumers in the digital age.\n\nYour Six Fundamental Consumer Rights:\n1. Right to Safety - Protection from hazardous goods and services\n2. Right to Information - Right to be informed about quality, quantity, price etc.\n3. Right to Choose - Access to competitive prices\n4. Right to be Heard - Your interests will receive due consideration\n5. Right to Redressal - Fair settlement of genuine grievances\n6. Right to Consumer Education - Knowledge of your rights\n\nWhere to file complaints:\n- District Consumer Commission: Claims up to Rs. 1 crore\n- State Consumer Commission: Claims between Rs. 1 crore and Rs. 10 crore  \n- National Consumer Commission: Claims above Rs. 10 crore\n\nYou can also file complaints online at consumerhelpline.gov.in",
      category: "consumer-rights",
      relevantLaws: JSON.stringify(["Consumer Protection Act, 2019", "Bureau of Indian Standards Act, 2016", "Legal Metrology Act, 2009"]),
      legalProvisions: JSON.stringify(["Section 2(7) - Definition of Consumer", "Section 35 - Complaint to District Commission", "Section 47 - Jurisdiction of State Commission"]),
      governmentResources: JSON.stringify(["National Consumer Helpline - 1800-11-4000", "Consumer Helpline Portal - consumerhelpline.gov.in", "CONFONET - confonet.nic.in"]),
    },
    {
      title: "Rights of Tenants Under Rent Control Laws",
      summary: "Tenants have protection from arbitrary eviction and excessive rent hikes under various state rent control acts.",
      content: "Rent control laws vary by state in India, but they generally provide basic protections to tenants:\n\nKey Tenant Rights:\n1. Protection from arbitrary eviction - Landlord cannot evict without valid legal grounds\n2. Protection from excessive rent hikes - Rent increases must follow prescribed limits\n3. Right to essential services - Water, electricity cannot be cut off to force eviction\n4. Right to receipt - Landlord must provide rent receipts\n5. Right to subletting - With landlord's written permission\n\nGrounds for valid eviction:\n- Non-payment of rent\n- Subletting without permission\n- Using premises for illegal purposes\n- Landlord's genuine need for personal use\n\nIf facing illegal eviction:\n1. Send a legal notice to the landlord\n2. File a case in Rent Control Court/Tribunal\n3. File complaint with local police for coercive eviction",
      category: "property-rights",
      relevantLaws: JSON.stringify(["Transfer of Property Act, 1882", "Model Tenancy Act, 2021", "State Rent Control Acts"]),
      legalProvisions: JSON.stringify(["Section 106 - Determination of lease", "Section 111 - Forfeiture of leases"]),
      governmentResources: JSON.stringify(["Ministry of Housing and Urban Affairs - mohua.gov.in", "Local Rent Control Authority"]),
    },
    {
      title: "Labour Rights: Minimum Wage and Working Hours",
      summary: "Every worker is entitled to minimum wages and regulated working hours as prescribed under the Minimum Wages Act and related laws.",
      content: "The Minimum Wages Act, 1948 ensures that workers receive at least the minimum wage set by the government for their category of work.\n\nKey Labour Rights:\n1. Minimum Wage - Every employer must pay at least the minimum wage notified by the government\n2. Working Hours - Maximum 9 hours per day and 48 hours per week\n3. Overtime - Overtime work must be paid at double the ordinary rate\n4. Weekly Rest - Every worker is entitled to one day of rest per week\n5. Leave with Pay - Workers are entitled to earned leave\n\nWhat to do if your rights are violated:\n1. File complaint with Labour Inspector in your area\n2. Approach Labour Commissioner's office\n3. File case before Labour Court/Industrial Tribunal\n4. Contact trade union for assistance",
      category: "labour-rights",
      relevantLaws: JSON.stringify(["Minimum Wages Act, 1948", "Factories Act, 1948", "Payment of Wages Act, 1936", "Code on Wages, 2019"]),
      legalProvisions: JSON.stringify(["Section 3 - Fixing of minimum rates of wages", "Section 11 - Wages in kind", "Section 14 - Overtime"]),
      governmentResources: JSON.stringify(["Ministry of Labour - labour.gov.in", "Labour Commissioner Office (State)", "eSHRAM Portal - eshram.gov.in"]),
    },
    {
      title: "Reporting Cyber Crime in India",
      summary: "Cyber crimes including online fraud, hacking, and cyberbullying can be reported to the Cyber Crime Cell or online at cybercrime.gov.in.",
      content: "With the rise of digital transactions and internet usage, cyber crimes have increased significantly. Here's how to protect yourself and report cyber crimes.\n\nCommon Cyber Crimes:\n1. Online financial fraud and phishing\n2. Hacking and unauthorized access\n3. Cyberbullying and online harassment\n4. Identity theft\n5. Morphing and revenge pornography\n6. Ransomware attacks\n\nHow to Report:\n1. Online: Report at cybercrime.gov.in (available 24/7)\n2. National Cyber Crime Reporting Helpline: 1930\n3. Visit your nearest police station's Cyber Crime Cell\n4. File an FIR under relevant sections of IT Act 2000\n\nImmediate steps after cyber fraud:\n- Contact your bank immediately to freeze transactions\n- Save all evidence (screenshots, emails, chat logs)\n- Do not delete any messages or notifications",
      category: "cyber-crime",
      relevantLaws: JSON.stringify(["Information Technology Act, 2000", "IT Amendment Act, 2008", "Indian Penal Code Sections 419, 420, 465, 468"]),
      legalProvisions: JSON.stringify(["Section 43 - Penalty for damage to computer systems", "Section 66 - Computer related offences", "Section 66C - Identity theft", "Section 66E - Violation of privacy"]),
      governmentResources: JSON.stringify(["National Cyber Crime Reporting Portal - cybercrime.gov.in", "National Cyber Crime Helpline: 1930", "CERT-In - cert-in.org.in"]),
    },
    {
      title: "Right to Information (RTI) - How to File an Application",
      summary: "Any citizen can request information from government bodies under the RTI Act 2005. The reply must be given within 30 days.",
      content: "The Right to Information Act, 2005 empowers every citizen of India to request information from any public authority. This is one of the most powerful tools for transparency and accountability.\n\nWhat you can ask for:\n- Copies of government documents and records\n- Status of pending applications and decisions\n- Information about government schemes and their beneficiaries\n- Details of government expenditure\n\nHow to file an RTI:\n1. Write an application addressed to the Public Information Officer (PIO)\n2. Pay a fee of Rs. 10 (waived for BPL card holders)\n3. Submit to the relevant government department\n4. You can also file online at rtionline.gov.in\n\nTimelines:\n- Normal response: 30 days\n- Life and liberty matters: 48 hours\n- If PIO is not appointed: Transfer to another authority within 5 days\n\nIf no response or wrong response:\n1. File First Appeal with Appellate Authority within 30 days\n2. File Second Appeal with Information Commission within 90 days",
      category: "rti",
      relevantLaws: JSON.stringify(["Right to Information Act, 2005", "Official Secrets Act, 1923 (exemptions)"]),
      legalProvisions: JSON.stringify(["Section 2 - Definitions of Public Authority and PIO", "Section 6 - Request for obtaining information", "Section 7 - Disposal of request", "Section 19 - Appeal"]),
      governmentResources: JSON.stringify(["Central RTI Portal - rtionline.gov.in", "Central Information Commission - cic.gov.in"]),
    },
    {
      title: "Constitutional Rights: Fundamental Rights of Every Indian Citizen",
      summary: "The Indian Constitution guarantees six fundamental rights to every citizen, including right to equality, freedom, and constitutional remedies.",
      content: "The Constitution of India under Part III (Articles 12-35) guarantees Fundamental Rights to every citizen. These rights are justiciable, meaning they can be enforced through courts.\n\nSix Categories of Fundamental Rights:\n\n1. Right to Equality (Articles 14-18)\n- Equality before law\n- Prohibition of discrimination on grounds of religion, race, caste, sex\n- Equality of opportunity in public employment\n- Abolition of untouchability\n\n2. Right to Freedom (Articles 19-22)\n- Freedom of speech and expression\n- Freedom to assemble peacefully\n- Freedom to move freely throughout India\n- Freedom to practice any profession\n\n3. Right Against Exploitation (Articles 23-24)\n- Prohibition of human trafficking\n- Prohibition of child labor below 14 years\n\n4. Right to Freedom of Religion (Articles 25-28)\n\n5. Cultural and Educational Rights (Articles 29-30)\n\n6. Right to Constitutional Remedies (Article 32)\n- Right to move Supreme Court for enforcement of fundamental rights\n- Writ jurisdiction: Habeas Corpus, Mandamus, Prohibition, Certiorari, Quo Warranto\n\nHow to enforce:\n- File writ petition in High Court (Article 226) or Supreme Court (Article 32)",
      category: "constitutional-rights",
      relevantLaws: JSON.stringify(["Constitution of India - Part III", "Protection of Civil Rights Act, 1955"]),
      legalProvisions: JSON.stringify(["Article 14 - Right to Equality", "Article 19 - Right to Freedom", "Article 21 - Right to Life and Personal Liberty", "Article 32 - Right to Constitutional Remedies"]),
      governmentResources: JSON.stringify(["Supreme Court of India - sci.gov.in", "National Human Rights Commission - nhrc.nic.in", "National Legal Services Authority - nalsa.gov.in"]),
    },
    {
      title: "Rights of Senior Citizens Under the 2007 Act",
      summary: "The Maintenance and Welfare of Parents and Senior Citizens Act 2007 provides for maintenance, residence, and protection of senior citizens.",
      content: "The Maintenance and Welfare of Parents and Senior Citizens Act, 2007 provides legal protection to senior citizens (persons aged 60 years or above) and parents.\n\nKey Provisions:\n1. Right to Maintenance - Children and legal heirs must maintain parents/senior citizens\n2. Right to Residence - Senior citizens cannot be dispossessed from their property\n3. Protection from Abandonment - Abandoning a senior citizen is a criminal offense punishable with imprisonment up to 3 months or fine up to Rs. 5,000\n\nMaintenance Tribunal:\n- Each district has a Maintenance Tribunal headed by SDM or equivalent\n- Application can be filed by senior citizen or authorized person\n- Tribunal can order maintenance up to Rs. 10,000 per month (in many states)\n- Order must be passed within 90 days\n\nHow to seek help:\n1. Approach local Maintenance Tribunal\n2. Contact District Social Welfare Officer\n3. Call Senior Citizen Helpline: 14567 (nationwide)",
      category: "senior-citizen-rights",
      relevantLaws: JSON.stringify(["Maintenance and Welfare of Parents and Senior Citizens Act, 2007", "Hindu Adoption and Maintenance Act, 1956"]),
      legalProvisions: JSON.stringify(["Section 4 - Maintenance of parents and senior citizens", "Section 22 - Protection of life and property of senior citizens", "Section 24 - Exposure and abandonment of senior citizens"]),
      governmentResources: JSON.stringify(["Ministry of Social Justice - socialjustice.gov.in", "Senior Citizen Helpline: 14567", "Elderline: 14567"]),
    },
  ]).onConflictDoNothing();

  // Complaint Templates
  await db.insert(complaintTemplatesTable).values([
    {
      type: "police_complaint",
      title: "Police Complaint",
      description: "File a complaint with the police station for criminal matters",
      questions: JSON.stringify([
        { id: "name", label: "Your Full Name", type: "text", placeholder: "Enter your full name", required: true },
        { id: "address", label: "Your Address", type: "text", placeholder: "Enter your full address", required: true },
        { id: "contact", label: "Contact Number", type: "text", placeholder: "Enter your mobile number", required: true },
        { id: "incident_date", label: "Date of Incident", type: "text", placeholder: "DD/MM/YYYY", required: true },
        { id: "incident_location", label: "Location of Incident", type: "text", placeholder: "Where did the incident occur?", required: true },
        { id: "accused_name", label: "Name of Accused (if known)", type: "text", placeholder: "Name of person responsible", required: false },
        { id: "incident_description", label: "Description of Incident", type: "textarea", placeholder: "Describe what happened in detail", required: true },
        { id: "witnesses", label: "Witnesses (if any)", type: "text", placeholder: "Names of witnesses", required: false },
        { id: "evidence", label: "Evidence Available", type: "text", placeholder: "What evidence do you have?", required: false },
      ]),
    },
    {
      type: "consumer_court",
      title: "Consumer Court Complaint",
      description: "File a consumer complaint for defective goods or deficient services",
      questions: JSON.stringify([
        { id: "name", label: "Your Full Name", type: "text", placeholder: "Enter your full name", required: true },
        { id: "address", label: "Your Address", type: "text", placeholder: "Enter your full address", required: true },
        { id: "contact", label: "Contact Number", type: "text", placeholder: "Enter your mobile number", required: true },
        { id: "opposite_party", label: "Name of Business/Seller", type: "text", placeholder: "Name of shop, company, or service provider", required: true },
        { id: "opposite_address", label: "Address of Business", type: "text", placeholder: "Address of the business", required: true },
        { id: "purchase_date", label: "Date of Purchase/Service", type: "text", placeholder: "DD/MM/YYYY", required: true },
        { id: "amount", label: "Amount Paid (Rs.)", type: "text", placeholder: "Amount you paid", required: true },
        { id: "complaint_details", label: "Nature of Complaint", type: "textarea", placeholder: "Describe the defect or deficiency in detail", required: true },
        { id: "relief_sought", label: "Relief/Compensation Sought", type: "textarea", placeholder: "What do you want as remedy?", required: true },
      ]),
    },
    {
      type: "labour_office",
      title: "Labour Office Complaint",
      description: "File a complaint for violation of labour laws including wages, conditions, or PF",
      questions: JSON.stringify([
        { id: "name", label: "Your Full Name", type: "text", placeholder: "Enter your full name", required: true },
        { id: "address", label: "Your Address", type: "text", placeholder: "Enter your full address", required: true },
        { id: "contact", label: "Contact Number", type: "text", placeholder: "Enter your mobile number", required: true },
        { id: "employer_name", label: "Name of Employer/Company", type: "text", placeholder: "Name of your employer", required: true },
        { id: "employer_address", label: "Employer's Address", type: "text", placeholder: "Address of the company", required: true },
        { id: "designation", label: "Your Designation", type: "text", placeholder: "Your job title or role", required: true },
        { id: "joining_date", label: "Date of Joining", type: "text", placeholder: "DD/MM/YYYY", required: true },
        { id: "complaint_details", label: "Nature of Violation", type: "textarea", placeholder: "Describe the labour law violation in detail", required: true },
        { id: "amount_due", label: "Amount Due (if applicable)", type: "text", placeholder: "Unpaid wages or dues", required: false },
      ]),
    },
    {
      type: "women_commission",
      title: "Women's Commission Complaint",
      description: "File a complaint with the National or State Women's Commission for violations of women's rights",
      questions: JSON.stringify([
        { id: "name", label: "Your Full Name", type: "text", placeholder: "Enter your full name", required: true },
        { id: "address", label: "Your Address", type: "text", placeholder: "Enter your full address", required: true },
        { id: "contact", label: "Contact Number", type: "text", placeholder: "Enter your mobile number", required: true },
        { id: "complaint_against", label: "Complaint Against (Name)", type: "text", placeholder: "Person or organization", required: true },
        { id: "relationship", label: "Relationship with Complainee", type: "text", placeholder: "e.g., husband, employer", required: true },
        { id: "nature_of_violation", label: "Nature of Violation", type: "text", placeholder: "e.g., domestic violence, harassment", required: true },
        { id: "incident_details", label: "Incident Details", type: "textarea", placeholder: "Describe all incidents in chronological order", required: true },
        { id: "steps_taken", label: "Steps Already Taken", type: "textarea", placeholder: "Have you filed a police complaint or any other action?", required: false },
        { id: "relief_sought", label: "Relief Sought", type: "textarea", placeholder: "What action do you want the Commission to take?", required: true },
      ]),
    },
    {
      type: "cyber_cell",
      title: "Cyber Crime Complaint",
      description: "Report online fraud, hacking, cyberbullying, or any cyber crime",
      questions: JSON.stringify([
        { id: "name", label: "Your Full Name", type: "text", placeholder: "Enter your full name", required: true },
        { id: "address", label: "Your Address", type: "text", placeholder: "Enter your full address", required: true },
        { id: "contact", label: "Contact Number", type: "text", placeholder: "Enter your mobile number", required: true },
        { id: "email", label: "Your Email Address", type: "text", placeholder: "Enter your email", required: true },
        { id: "crime_type", label: "Type of Cyber Crime", type: "text", placeholder: "e.g., online fraud, hacking, cyberbullying", required: true },
        { id: "crime_date", label: "Date of Incident", type: "text", placeholder: "DD/MM/YYYY", required: true },
        { id: "platform", label: "Platform/Website Involved", type: "text", placeholder: "e.g., Facebook, WhatsApp, Bank website", required: false },
        { id: "amount_lost", label: "Amount Lost (if financial fraud)", type: "text", placeholder: "Amount lost in Rs.", required: false },
        { id: "incident_details", label: "Incident Details", type: "textarea", placeholder: "Describe what happened, including all URLs, account numbers, transaction IDs", required: true },
      ]),
    },
  ]).onConflictDoNothing();

  // Legal Journeys
  await db.insert(journeysTable).values([
    {
      title: "Filing a Domestic Violence Complaint",
      description: "A step-by-step guide to seek protection and legal remedies under the Domestic Violence Act 2005",
      category: "family-law",
      estimatedDays: 30,
      eligibility: "Women who are or have been in a domestic relationship and have experienced physical, emotional, sexual, or economic abuse",
      requiredDocuments: JSON.stringify(["Identity proof (Aadhaar/PAN)", "Address proof", "Photos of injuries (if any)", "Medical reports (if applicable)", "Witness statements", "Any previous police complaints"]),
      applicableLaws: JSON.stringify(["Protection of Women from Domestic Violence Act, 2005", "Indian Penal Code Section 498A", "Code of Criminal Procedure"]),
      steps: JSON.stringify([
        { stepNumber: 1, title: "Contact a Protection Officer", description: "Locate and contact the Protection Officer in your district. They are designated officials who help domestic violence victims.", tips: "You can find the Protection Officer's contact through the District Legal Services Authority or local Women's Helpline 181" },
        { stepNumber: 2, title: "File a Domestic Incident Report (DIR)", description: "The Protection Officer will help you file a Domestic Incident Report. This is the official record of the violence.", tips: "Be as detailed as possible. Include dates, types of abuse, and any witnesses" },
        { stepNumber: 3, title: "Apply for a Protection Order", description: "File an application in the Magistrate's Court for a Protection Order to prevent further violence.", tips: "The Magistrate can grant an ex-parte (one-sided) order on the very first day if immediate protection is needed" },
        { stepNumber: 4, title: "Seek a Residence Order", description: "If you need to stay in the shared household, apply for a Residence Order that prevents your abuser from throwing you out.", tips: "Even if the house is not in your name, you have the right to stay under the PWDVA" },
        { stepNumber: 5, title: "Apply for Monetary Relief", description: "File for monetary relief including maintenance, medical expenses, and compensation for losses suffered.", tips: "Keep all bills, medical records, and expenses documented" },
        { stepNumber: 6, title: "File Police FIR (if needed)", description: "For serious physical assault, file an FIR with the police under Section 498A IPC (cruelty by husband/relatives).", tips: "You can take the help of a lawyer or Protection Officer to ensure your FIR is properly registered" },
      ]),
    },
    {
      title: "Property Dispute Resolution",
      description: "Navigate through property disputes including boundary disputes, inheritance claims, and illegal occupancy",
      category: "property-law",
      estimatedDays: 180,
      eligibility: "Any person with a legitimate claim or legal right over a property",
      requiredDocuments: JSON.stringify(["Original property documents/title deed", "Sale deed or gift deed", "Mutation/khata certificate", "Property tax receipts", "Encumbrance certificate", "Survey/sketch of property"]),
      applicableLaws: JSON.stringify(["Transfer of Property Act, 1882", "Registration Act, 1908", "Specific Relief Act, 1963", "Indian Succession Act, 1925"]),
      steps: JSON.stringify([
        { stepNumber: 1, title: "Gather All Property Documents", description: "Collect all original documents related to the property including title deed, sale deed, tax receipts, and encumbrance certificate.", tips: "Get certified copies from Sub-Registrar's office if originals are missing" },
        { stepNumber: 2, title: "Send Legal Notice", description: "Send a legal notice to the opposing party through an advocate, stating your claims and giving them a chance to resolve the matter.", tips: "The notice should be sent via registered post with acknowledgment due" },
        { stepNumber: 3, title: "Try Mediation/Lok Adalat", description: "Before going to court, try to resolve the dispute through mediation or Lok Adalat. It's faster and cheaper.", tips: "Contact your District Legal Services Authority for free mediation services" },
        { stepNumber: 4, title: "File Case in Civil Court", description: "If mediation fails, file a civil suit in the appropriate court (Munsiff Court for lower value, District Court for higher).", tips: "File a temporary injunction to prevent the opposite party from selling or modifying the property during dispute" },
        { stepNumber: 5, title: "Present Evidence", description: "Submit all documentary evidence and witness testimonies to support your claim.", tips: "A local advocate familiar with land records can be very helpful" },
        { stepNumber: 6, title: "Get Decree Executed", description: "Once you win the case, apply for execution of the court decree to take possession of the property.", tips: "The Execution Court will help you take physical possession if the other party refuses" },
      ]),
    },
    {
      title: "Filing a Consumer Complaint",
      description: "Step-by-step process to file and win a consumer complaint for defective goods or poor services",
      category: "consumer-law",
      estimatedDays: 90,
      eligibility: "Any person who has purchased goods or availed services for personal use",
      requiredDocuments: JSON.stringify(["Purchase receipt/invoice", "Warranty card", "Communication with seller", "Photos of defective product", "Bank/payment records", "Any medical records (if health affected)"]),
      applicableLaws: JSON.stringify(["Consumer Protection Act, 2019", "Sale of Goods Act, 1930", "Bureau of Indian Standards Act"]),
      steps: JSON.stringify([
        { stepNumber: 1, title: "Communicate with the Seller", description: "First, reach out to the seller or service provider formally via email or letter, requesting resolution.", tips: "Keep copies of all communication. This shows you tried to resolve the issue first" },
        { stepNumber: 2, title: "File Complaint with National Consumer Helpline", description: "Call 1800-11-4000 or log complaint at consumerhelpline.gov.in before filing in court.", tips: "Many complaints are resolved at this stage itself without going to court" },
        { stepNumber: 3, title: "Prepare Your Complaint", description: "Draft a detailed complaint mentioning: parties involved, facts, relief sought, and documents.", tips: "Complaints below Rs. 1 crore go to District Consumer Commission" },
        { stepNumber: 4, title: "File in Consumer Commission", description: "File the complaint with required fees at the District Consumer Commission or online on CONFONET.", tips: "Fee is very nominal (Rs. 200-500 for most cases). No lawyer required" },
        { stepNumber: 5, title: "Appear for Hearing", description: "Attend hearings and present your evidence. Consumer courts are designed to be consumer-friendly.", tips: "You can represent yourself - you don't need to hire a lawyer" },
        { stepNumber: 6, title: "Receive Compensation", description: "The Commission will order refund, replacement, or compensation if your case is successful.", tips: "The process typically takes 3-6 months. You can also appeal to higher commission if needed" },
      ]),
    },
    {
      title: "RTI Application Process",
      description: "File an RTI application to get information from government bodies within 30 days",
      category: "citizen-rights",
      estimatedDays: 45,
      eligibility: "Any citizen of India",
      requiredDocuments: JSON.stringify(["Written application in Hindi or English", "Application fee of Rs. 10 (money order/demand draft/cash)", "Identity proof"]),
      applicableLaws: JSON.stringify(["Right to Information Act, 2005"]),
      steps: JSON.stringify([
        { stepNumber: 1, title: "Identify the Public Authority", description: "Identify which government department or body holds the information you need.", tips: "You can file RTI with any government body - central, state, or local" },
        { stepNumber: 2, title: "Write Your Application", description: "Write a clear, specific application in Hindi or English to the Public Information Officer (PIO).", tips: "Be specific about what information you want. You don't need to give reasons" },
        { stepNumber: 3, title: "Pay the Fee", description: "Pay Rs. 10 application fee. For BPL card holders, the fee is waived.", tips: "You can file online at rtionline.gov.in without going to the office" },
        { stepNumber: 4, title: "Submit and Track", description: "Submit the application and note the registration number for tracking.", tips: "The PIO must respond within 30 days (48 hours for life and liberty matters)" },
        { stepNumber: 5, title: "File First Appeal if Needed", description: "If no response within 30 days or unsatisfied with response, file First Appeal with Appellate Authority.", tips: "First appeal must be filed within 30 days of the deadline or receipt of unsatisfactory response" },
        { stepNumber: 6, title: "File Second Appeal if Needed", description: "If First Appeal fails, file Second Appeal with State/Central Information Commission within 90 days.", tips: "The Information Commission can impose penalty on PIO up to Rs. 25,000 for delays" },
      ]),
    },
  ]).onConflictDoNothing();

  // Government Schemes
  await db.insert(schemesTable).values([
    {
      title: "PM Awas Yojana (Urban)",
      description: "Provides affordable housing to urban poor including slum dwellers through credit linked subsidy and government funding",
      category: "housing",
      eligibility: "Economically Weaker Section (EWS), Lower Income Group (LIG), and Middle Income Group (MIG) families who do not own a house",
      benefits: "Interest subsidy of 3-6.5% on home loans. Beneficiaries can save up to Rs. 2.67 lakhs. Government also provides direct financial assistance for construction.",
      requiredDocuments: JSON.stringify(["Aadhaar card", "Income certificate", "Address proof", "Bank account details", "Passport size photographs", "Property documents (if applicable)"]),
      applicationProcess: "Apply online at pmaymis.gov.in or visit your local Common Service Centre (CSC) or municipal corporation office. Fill the application form and submit required documents.",
      officialLink: "https://pmaymis.gov.in",
      ministry: "Ministry of Housing and Urban Affairs",
    },
    {
      title: "PM Jan Arogya Yojana (Ayushman Bharat)",
      description: "World's largest government-funded health insurance scheme providing coverage of Rs. 5 lakhs per family per year",
      category: "healthcare",
      eligibility: "Families covered under SECC-2011 database, RSBY beneficiaries. Covers about 10.74 crore poor and vulnerable families.",
      benefits: "Rs. 5 lakh health insurance cover per family per year for hospitalization. Covers pre and post-hospitalization expenses. Cashless treatment at empanelled hospitals.",
      requiredDocuments: JSON.stringify(["Aadhaar card", "Ration card", "Mobile number linked to Aadhaar", "Family details as per SECC data"]),
      applicationProcess: "Check eligibility at mera.pmjay.gov.in or call 14555. Visit any empanelled hospital with Aadhaar and a Beneficiary Identification System (BIS) card will be issued.",
      officialLink: "https://pmjay.gov.in",
      ministry: "Ministry of Health and Family Welfare",
    },
    {
      title: "PM Ujjwala Yojana",
      description: "Provides free LPG connections to women from Below Poverty Line (BPL) households to promote clean cooking fuel",
      category: "energy",
      eligibility: "Women from BPL households who do not have an existing LPG connection. Must be above 18 years of age.",
      benefits: "Free LPG connection including deposit-free cylinder and stove. First refill may also be subsidized in some states.",
      requiredDocuments: JSON.stringify(["Aadhaar card", "BPL ration card", "Bank account details", "Proof of address", "Passport size photo"]),
      applicationProcess: "Visit your nearest LPG distributor with required documents. Fill Form 1 (for KYC) and Form 2 (for PMUY). The distributor will verify documents and provide the free connection.",
      officialLink: "https://pmuy.gov.in",
      ministry: "Ministry of Petroleum and Natural Gas",
    },
    {
      title: "PM Kisan Samman Nidhi",
      description: "Provides income support of Rs. 6,000 per year to small and marginal farmers across India",
      category: "agriculture",
      eligibility: "All land-holding farmers with cultivable land up to 2 hectares. Excludes institutional land holders, income tax payers, and constitutional position holders.",
      benefits: "Rs. 6,000 per year transferred directly to bank account in 3 equal installments of Rs. 2,000 every four months.",
      requiredDocuments: JSON.stringify(["Aadhaar card", "Land records/Khatian", "Bank account details (linked to Aadhaar)", "Mobile number"]),
      applicationProcess: "Register online at pmkisan.gov.in or visit Common Service Centre. State governments verify and upload farmer data. Funds are directly transferred to bank account.",
      officialLink: "https://pmkisan.gov.in",
      ministry: "Ministry of Agriculture and Farmers Welfare",
    },
    {
      title: "National Legal Services Authority (NALSA) - Free Legal Aid",
      description: "Provides free legal services to eligible citizens including representation in courts and access to legal advice",
      category: "legal",
      eligibility: "Persons in custody, victims of trafficking, SC/ST communities, women, children, disabled persons, industrial workmen, persons in difficult circumstances, and persons with annual income below Rs. 3 lakhs",
      benefits: "Free legal representation in all courts and tribunals. Free legal advice and counseling. Free drafting of legal documents. Access to Lok Adalat for quick dispute resolution.",
      requiredDocuments: JSON.stringify(["Identity proof", "Income certificate (if applying on income grounds)", "Documents related to the case"]),
      applicationProcess: "Visit the District Legal Services Authority (DLSA) in your district. Fill the application form and submit supporting documents. You will be assigned a panel lawyer.",
      officialLink: "https://nalsa.gov.in",
      ministry: "Ministry of Law and Justice / Supreme Court of India",
    },
    {
      title: "Pradhan Mantri Mudra Yojana (PMMY)",
      description: "Provides loans up to Rs. 10 lakhs to non-corporate, non-farm small/micro enterprises for business activities",
      category: "business",
      eligibility: "Any Indian citizen who has a business plan for income-generating activities in manufacturing, trading or service sector. Not applicable for agricultural activities.",
      benefits: "Shishu: Loans up to Rs. 50,000. Kishore: Loans from Rs. 50,001 to Rs. 5 lakhs. Tarun: Loans from Rs. 5 lakhs to Rs. 10 lakhs. No collateral required for Shishu loans.",
      requiredDocuments: JSON.stringify(["Identity proof", "Address proof", "Business plan/quotations", "Bank statements (6 months)", "Passport photos", "Caste certificate (if applicable)"]),
      applicationProcess: "Apply at any bank, NBFC, or MFI. You can also apply online at udyamimitra.in. The loan is sanctioned based on business viability.",
      officialLink: "https://mudra.org.in",
      ministry: "Ministry of Finance",
    },
  ]).onConflictDoNothing();

  // Learning Content
  await db.insert(learningContentTable).values([
    {
      title: "What is an FIR and How to File One",
      summary: "A First Information Report (FIR) is the first step in reporting a cognizable offence to the police. Learn when and how to file one.",
      content: "A First Information Report (FIR) is a written document prepared by the police when they receive information about the commission of a cognizable offence. It is the first step in the criminal justice process.\n\nWHEN TO FILE AN FIR:\n- For cognizable offences (serious crimes where police can arrest without warrant)\n- Theft, robbery, assault, rape, murder, cheating, kidnapping etc.\n- For non-cognizable offences, you file a Non-Cognizable Report (NCR)\n\nHOW TO FILE:\n1. Go to the nearest police station\n2. Report the incident to the duty officer\n3. The officer must register the FIR (they cannot refuse for cognizable offences)\n4. Get a copy of the FIR for free - it is your right\n5. Note the FIR number for tracking\n\nIF POLICE REFUSE TO FILE FIR:\n1. Send written complaint by post to the Superintendent of Police\n2. File a complaint before the Magistrate under Section 156(3) CrPC\n3. Contact State/District Police Complaint Authority\n4. Approach National Human Rights Commission\n\nIMPORTANT: Under Section 166A IPC, a police officer who refuses to register an FIR for rape can be punished with imprisonment.",
      type: "article",
      tags: JSON.stringify(["police", "fir", "complaint", "criminal law", "basics"]),
    },
    {
      title: "Understanding Your Rights During Police Interrogation",
      summary: "Know your rights if you are questioned, detained, or arrested by the police.",
      content: "Many people don't know their rights when dealing with the police. Here's what you need to know.\n\nIF YOU ARE QUESTIONED (not arrested):\n- You are not obligated to answer all questions\n- You can refuse to give statement\n- You can ask to speak to a lawyer\n\nIF YOU ARE ARRESTED:\n- Right to know the grounds of arrest (Article 22, Constitution)\n- Right to be produced before Magistrate within 24 hours\n- Right to informed of charges\n- Right to consult a lawyer of your choice\n- Right to legal aid if you cannot afford a lawyer\n- Right to remain silent (you cannot be forced to confess)\n\nPROTECTION AGAINST CUSTODIAL TORTURE:\n- Under no circumstances can police legally torture you\n- File complaint with State Human Rights Commission\n- File writ of Habeas Corpus in High Court\n\nIMPORTANT NUMBERS:\n- National Human Rights Commission: nhrc.nic.in\n- Legal Aid: Contact District Legal Services Authority",
      type: "article",
      tags: JSON.stringify(["police", "arrest", "rights", "custody", "fundamental rights"]),
    },
    {
      title: "How to Write an Effective Legal Notice",
      summary: "A legal notice is a formal communication sent before filing a case. Learn how to write one effectively.",
      content: "A legal notice is a formal written communication sent to a person or organization, informing them of your legal claim and giving them a chance to resolve the matter before you take legal action.\n\nWHEN TO SEND A LEGAL NOTICE:\n- Property disputes\n- Consumer complaints\n- Employment disputes\n- Recovery of money\n- Defamation claims\n- Contract disputes\n\nESSENTIAL ELEMENTS:\n1. Date and place\n2. Full name and address of sender\n3. Full name and address of recipient\n4. Facts of the case in chronological order\n5. Legal provisions violated\n6. Relief/remedy sought\n7. Time given to respond (usually 15-30 days)\n8. Consequences if not complied with\n\nHOW TO SEND:\n- Always send by registered post with acknowledgment due\n- Keep a copy for your records\n- An advocate can send it on legal letterhead for more impact\n\nAFTER SENDING:\n- If recipient responds positively, try to settle\n- If no response or negative response, proceed with legal action\n- The legal notice creates a paper trail that helps in court",
      type: "article",
      tags: JSON.stringify(["legal notice", "procedure", "dispute resolution", "documentation"]),
    },
    {
      title: "FAQ: Can I be evicted from my home without a court order?",
      summary: "No, a landlord cannot forcibly evict you without following due legal process and obtaining a court order.",
      content: "Q: My landlord is threatening to throw me out. What are my rights?\n\nA: Your landlord cannot evict you without following legal procedure, regardless of the reason. Here's what the law says:\n\nLEGAL PROCESS FOR EVICTION:\n1. Landlord must give you proper notice (usually 15-30 days)\n2. Must file an eviction suit in Rent Control Court or Civil Court\n3. Must prove valid grounds for eviction\n4. Court will hear your side\n5. Only if court passes an eviction order can you be asked to leave\n\nVALID GROUNDS FOR EVICTION:\n- Non-payment of rent (with proper notice period)\n- Subletting without permission\n- Using premises for illegal activities\n- Landlord's bona fide personal need\n- Structural repairs making building unsafe\n\nILLEGAL EVICTION:\n- Cutting off electricity or water to force you out\n- Locking the property while you are inside\n- Physically removing your belongings\n- Threatening or intimidating you\n\nIF FACING ILLEGAL EVICTION:\n1. Call police immediately (it's a criminal offense)\n2. Get a lawyer and file for urgent injunction\n3. File complaint with Local SDM/District Collector",
      type: "faq",
      tags: JSON.stringify(["tenant rights", "eviction", "landlord", "property", "housing"]),
    },
    {
      title: "Tip: 5 Documents Every Indian Should Keep Safe",
      summary: "These 5 essential documents can save you significant time and trouble in legal matters.",
      content: "1. AADHAAR CARD\nThe most important identity document in India. Keep physical and digital copies. Link it to your bank account, mobile number, and all government services.\n\n2. PAN CARD\nEssential for all financial transactions above Rs. 50,000, income tax filing, and opening bank accounts. Link it to your Aadhaar.\n\n3. PROPERTY DOCUMENTS\nIf you own property, keep original sale deed, title deed, and mutation records in a safe place. Get a certified copy from the Sub-Registrar if originals are lost.\n\n4. BIRTH CERTIFICATE\nYour birth certificate is the proof of your age and birthplace. Many rights and entitlements depend on it. Apply for a new one from your Municipal Corporation if lost.\n\n5. EDUCATIONAL CERTIFICATES\nAll your school and college certificates. These cannot be replaced easily. Store digital copies in DigiLocker (digilocker.gov.in) - a government-backed secure digital platform.\n\nBONUS TIP: DigiLocker\nSign up for DigiLocker. It's free, government-backed, and lets you store and share all your important documents digitally. Many authorities now accept DigiLocker documents.",
      type: "tip",
      tags: JSON.stringify(["documents", "aadhaar", "pan", "digilocker", "essential", "tips"]),
    },
  ]).onConflictDoNothing();

  // Legal Aid Providers
  await db.insert(legalAidProvidersTable).values([
    {
      name: "District Legal Services Authority - Mumbai",
      type: "dlsa",
      city: "Mumbai",
      state: "Maharashtra",
      pincode: "400001",
      address: "City Civil Court Complex, Dhobi Talao, Mumbai - 400001",
      phone: "022-22620507",
      email: "dlsa.mumbai@gmail.com",
      website: "https://nalsa.gov.in",
      practiceAreas: JSON.stringify(["Criminal Law", "Family Law", "Property Law", "Consumer Rights", "Labour Law", "RTI"]),
      languages: JSON.stringify(["English", "Hindi", "Marathi"]),
      rating: 4.2,
      description: "Government-funded legal aid authority providing free legal services to eligible citizens in Mumbai district.",
    },
    {
      name: "Majlis Manch - Legal Aid for Women",
      type: "ngo",
      city: "Mumbai",
      state: "Maharashtra",
      pincode: "400010",
      address: "Flat No 9, 2nd Floor, Plot 29, Juhu Development Scheme, Vile Parle West, Mumbai",
      phone: "022-26106699",
      email: "majlislaw@gmail.com",
      website: "https://majlislaw.com",
      practiceAreas: JSON.stringify(["Domestic Violence", "Sexual Harassment", "Divorce", "Child Custody", "Women's Rights"]),
      languages: JSON.stringify(["English", "Hindi", "Marathi"]),
      rating: 4.8,
      description: "Leading NGO providing free legal aid to women survivors of violence and those facing legal issues related to family, property, and rights.",
    },
    {
      name: "District Legal Services Authority - Delhi",
      type: "dlsa",
      city: "New Delhi",
      state: "Delhi",
      pincode: "110003",
      address: "Patiala House Court Complex, New Delhi - 110003",
      phone: "011-23073975",
      email: "dlsa-delhi@nic.in",
      website: "https://dslsa.org",
      practiceAreas: JSON.stringify(["Criminal Law", "Civil Law", "Family Law", "Labour Law", "Consumer Rights"]),
      languages: JSON.stringify(["English", "Hindi"]),
      rating: 4.0,
      description: "Delhi State Legal Services Authority providing free legal aid and Lok Adalat services across Delhi.",
    },
    {
      name: "Human Rights Law Network",
      type: "ngo",
      city: "New Delhi",
      state: "Delhi",
      pincode: "110001",
      address: "576, Masjid Road, Jangpura, New Delhi - 110014",
      phone: "011-24374501",
      email: "admin@hrln.org",
      website: "https://hrln.org",
      practiceAreas: JSON.stringify(["Human Rights", "Criminal Law", "Women's Rights", "Disability Rights", "Child Rights", "Environmental Law"]),
      languages: JSON.stringify(["English", "Hindi"]),
      rating: 4.6,
      description: "National network of lawyers working for human rights, providing free legal aid to marginalized communities across India.",
    },
    {
      name: "Advocate Sunita Verma",
      type: "lawyer",
      city: "Bengaluru",
      state: "Karnataka",
      pincode: "560001",
      address: "Chamber No. 215, City Civil Court, Bengaluru - 560001",
      phone: "9845012345",
      email: "sunita.verma.advocate@gmail.com",
      website: null,
      practiceAreas: JSON.stringify(["Family Law", "Property Disputes", "Consumer Cases", "Women's Rights"]),
      languages: JSON.stringify(["English", "Hindi", "Kannada"]),
      rating: 4.5,
      description: "Experienced advocate with 15+ years of practice in family law and women's rights cases. Offers consultation at subsidized rates for low-income clients.",
    },
    {
      name: "Karnataka State Legal Services Authority",
      type: "dlsa",
      city: "Bengaluru",
      state: "Karnataka",
      pincode: "560001",
      address: "High Court of Karnataka, Dr. Ambedkar Veedhi, Bengaluru - 560001",
      phone: "080-22113404",
      email: "ksla@ksla.gov.in",
      website: "https://ksla.nic.in",
      practiceAreas: JSON.stringify(["All Civil Matters", "Criminal Law", "Family Law", "Property Law", "Labour Law"]),
      languages: JSON.stringify(["English", "Kannada", "Hindi"]),
      rating: 4.1,
      description: "State legal services authority providing free legal aid through panel advocates and Lok Adalats across Karnataka.",
    },
  ]).onConflictDoNothing();

  console.log("Seed completed successfully!");
  process.exit(0);
}

seed().catch(err => {
  console.error("Seed failed:", err);
  process.exit(1);
});
